baseURL = "https://joeymays.xyz"
languageCode = "en-us"
title = "Joey Mays"
theme = "hugo-profile"
pluralizeListTitles = "false"

Paginate = 3
#disqusShortname = ""
googleAnalytics = "G-WHEWNK58B8"

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog"
url = "/blog"
weight = 1

# [[Menus.main]]
# identifier = "gallery"
# name = "Gallery"
# title = "Blog posts"
# url = "/gallery"
# weight = 2

[params]
title = "Joey Mays"
description = "Joey Mays's Personal Website"
favicon = "/assets/atom.png"
useBootstrapCDN = false

  [params.theme]
  disableThemeToggle = false
  defaultTheme = "dark"

  [params.color]
  textColor = "#39393A" #all text, including hi my name and subtitles
  secondaryTextColor = "#000000" #section headings
  backgroundColor = "" #site background
  secondaryBackgroundColor = "" # not sure
  primaryColor = "#39393A" #name, banner name, icon borders
  secondaryColor = "" #card backgrounds
  publicationURLColor = ""

  [params.color.darkmode]
  textColor = ""
  secondaryTextColor = ""
  backgroundColor = ""
  secondaryBackgroundColor = ""
  primaryColor = ""
  secondaryColor = ""
  publicationURLColor = ""


  [params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Joey."
  subtitle = "I'm a PhD candidate at the NYU School of Medicine."
  content = "I develop methods for detecting aneuploidy in cells and create tools to make my labmates' lives easier."
  image = "/jmheadshot.png"

    [params.hero.button]
    enable = true
    name = "CV"
    url = "/Joseph_Mays_CV_Fall2022.pdf"
    download = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fa fa-envelope-open"
url = "mailto:josephcmays@gmail.com"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/joeymays"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/josephmays2/"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-twitter"
url = "https://twitter.com/josephcmays"

[[params.hero.socialLinks.customIcons]]
icon = "/assets/ORCID_iD.png"
url = "https://orcid.org/0000-0003-4903-938X"





  [params.about]
  enable = false
  title = "About Me"
  image = "/images/me.png"
  content = """
I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA.

I am currently working on a project that will be used to help people find the best way to get around the city."""

    [params.about.skills]
    enable = false
    title = "Here are a few technologies I've been working with recently:"
    items = [ "HTML", "CSS", "JavaScript", "React", "Node", "Express" ]

  [params.experience]
  enable = false

    [[params.experience.items]]
    job = "Senior Software Developer"
    company = "Facebook"
    companyUrl = "https://example.com"
    date = "Jan 2022 - present"
    content = "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      [params.experience.items.featuredLink]
      enable = true
      name = "View the project"
      url = "https://example.com"

    [[params.experience.items]]
    job = "Software Developer"
    company = "Amazon"
    companyUrl = "https://example.com"
    date = "Sep 2020 - Dec 2021"
    content = """
I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

- Lead backend developer for a product.
- Created a frontend design for a product.
"""

      [params.experience.items.featuredLink]
      enable = true
      url = "https://example.com"

      [params.experience.items.info]
      enable = true
      content = "I worked as a software developer for more than one year in Amazon."

    [[params.experience.items]]
    job = "Junior Software Developer"
    company = "Apple"
    companyUrl = "https://example.com"
    date = "Jan 2020 - Aug 2020"
    content = """
I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

- Lead backend developer for a product.
- Created a frontend design for a product.
"""

      [params.experience.items.info]
      enable = false

      [params.experience.items.featuredLink]
      enable = true
      url = "https://example.com"

    [[params.experience.items]]
    job = "UI/UX Designer"
    company = "Netflix"
    companyUrl = "https://example.com"
    date = "June 2017 - Nov 2019"
    content = """
I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

- Lead backend developer for a product.
- Created a frontend design for a product.
"""

      [params.experience.items.featuredLink]
      enable = true
      url = "https://example.com"

    [[params.experience.items]]
    job = "Product Designer"
    company = "Google"
    companyUrl = "https://example.com"
    date = "Feb 2016 - Mar 2017"
    content = "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  [params.education]
  enable = true

    [[params.education.items]]
    title = "Single-cell RNA sequencing of the mammalian pineal gland identifies two pinealocyte subtypes and cell type-specific daily patterns of gene expression."
    date = "Oct 2018"
    # GPA = ""
    content = "**<u>Joseph C. Mays</u>**, Michael C. Kelly, ... Matthew W. Kelley, David C. Klein"

      [params.education.items.school]
      name = 'PLOS One'
      url = "https://doi.org/10.1371/journal.pone.0205883"

      [params.education.items.featuredLink]
      enable = true
      name = "Github Codebook"
      url = "https://github.com/joeymays/PinealGland_SingleCell"

    [[params.education.items]]
    title = "Characterization of the development of the mouse cochlear epithelium at the single cell level"
    date = "Dec 2020"
    # GPA = ""
    content = "Likhitha Kolla, Michael C. Kelly, ... **<u>Joseph C. Mays</u>**, ... Matthew W. Kelley"

      [params.education.items.school]
      name = "Nature Communications"
      url = "https://doi.org/10.1038/s41467-020-16113-y"

      [params.education.items.featuredLink]
      enable = false
      name = ""
      url = "https://example.com"

    [[params.education.items]]
    title = "Not all cancers are created equal: Tissue specificity in cancer genes and pathways"
    date = "April 2020"
    # GPA = ""
    content = "Joy J. Bianchi, Xin Zhao, **<u>Joseph C. Mays</u>**, Teresa Davoli"

      [params.education.items.school]
      name = "Current Opinion in Cell Biology"
      url = "https://doi.org/10.1016/j.ceb.2020.01.005"

      [params.education.items.featuredLink]
      enable = false
      name = ""
      url = "https://example.com"

    [[params.education.items]]
    title = "Single Cell Sequencing of the Pineal Gland: The Next Chapter"
    date = "Sept 2020"
    # GPA = ""
    content = "Steven L. Coon, ... **<u>Joseph C. Mays</u>**, Michael C. Kelly, Matthew W. Kelley, ... David C. Klien"

        [params.education.items.school]
        name = "Frontiers in Endocrinology"
        url = "https://doi.org/10.3389/fendo.2019.00590"

        [params.education.items.featuredLink]
        enable = false
        name = ""
        url = ""

  [params.achievements]
  enable = false

    [[params.achievements.items]]
    title = "Google kickstart runner"
    content = "I solved all problems with optimal solution."
    url = "https://example.com"

    [[params.achievements.items]]
    title = "Facebook Hackathon Winner"
    content = "Developed a product using Artificial Intelligence."

    [[params.achievements.items]]
    title = "Hugo Profile"
    content = "Developed a theme and getting 1K+ downloads per month."
    url = "https://github.com/gurusabarish/hugo-profile"

    [[params.achievements.items]]
    title = "Microsoft Imagine Runner"
    content = "We are developed a product which can help others."

    [[params.achievements.items]]
    title = "Google Summer of Code"
    content = "Contributed to a open source project."
    url = "https://example.com"

  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "GetChromosomes"
    content = "R Shiny app for quick chromosome and cytoband annotation for genes."
    image = "assets/bar-purple.png"

      [params.projects.items.featured]
      name = "Launch App"
      link = "https://joeymays.shinyapps.io/getChromosomes/"

      [[params.projects.items.links]]
      # icon = "fab fa-github"
      name = "GitHub"
      url = "https://github.com/joeymays/get-chromosomes"

      # [[params.projects.items.links]]
      # icon = "fa fa-envelope"
      # url = ""
      #
      # [[params.projects.items.links]]
      # icon = "fab fa-github"
      # url = ""
      #
      # [[params.projects.items.links]]
      # icon = "fab fa-twitter"
      # url = ""

    [[params.projects.items]]
    title = "NGS Pooling Calculator"
    content = "R Shiny calculator for Illumina Next Gen Sequencing library pooling."
    image = "assets/bar-green.png"

      [params.projects.items.featured]
      name = "Launch App"
      link = "https://joeymays.shinyapps.io/ngs-pooling/"

      [[params.projects.items.links]]
      # icon = "fab fa-github"
      name = "GitHub"
      url = "https://github.com/joeymays/ngs-pooling"

    [[params.projects.items]]
    title = "QuantIT Calculator"
    content = "R Shiny calculator for QuantIT dsDNA quanitification kits."
    image = "assets/bar-orange.png"

      [params.projects.items.featured]
      name = "Launch App"
      link = "https://joeymays.shinyapps.io/quantitcalculator"

      [[params.projects.items.links]]
      name = "GitHub"
      url = "https://github.com/joeymays/quantIT-calculator"

  [params.contact]
  enable = false
  content = "My inbox is always open."
  email = "josephcmays@gmail.com"
  btnName = "Email Me"

# [params.footer.socialNetworks]
# github = "https://github.com"
# linkedin = "https://linkedin.com"
# twitter = "https://twitter.com"
# instagram = "https://instagram.com"
# facebook = "https://facebook.com"
